### ISSUE TITLE
how to set value to property [name , age] using the type Proxied<Cat>

### ISSUE THREAD

**Issue by chrismichaelps** [slavik57/typescript-playground#1]
Hi @slavik57 ,

I was practicing with the URL example,

`https://github.com/slavik57/typescript-playground/blob/master/src/advancedTypes/mappedTypes.ts`

I was trying to figure out how to assign values to the [age, name] property using set (), but it shows me an error that you can see below.

If there is a way to correct the error, I will appreciate it.

**index.ts**

```typescript
interface Proxy<T>{
  get(): T;
  set(value: T): void;
}

type Proxied<T> = {
  [P in keyof T]: Proxy<T[P]>;
}

interface Cat{
  age: number;
  name: string;
}


type PC = Proxied<Cat>;

const doc: PC = {
  name: doc.name.set("red"),
  age: doc.age.set(2)
};

console.log(doc.age.get());
```

**output**

```shell
  src/typetify.ts:29:7
    29 const doc: PC = {
             ~~~
    'doc' is declared here.
src/typetify.ts:31:8 - error TS2454: Variable 'doc' is used before being assigned.

31   age: doc.age.set(24)
          ~~~
```

**Comment by slavik57** [comment]
The issue you have here is that you define the `doc` raviable in the same line you are using it.
You will get the same error when you try to do something like this:
```
const x = x + 1;
```
It's basically the same thing you are doing here.
To initialize the `doc` variable that corresponds to your `PC` interface you'll need to do:
```
const doc: PC = {
  name: { value: "red", get() { return value }, set(newValue) { value = newValue }
  age: { value: 2, get() { return value }, set(newValue) { value = newValue }
}
```

Another approach is to create a `Property` class and use it in the `doc`
```
class Property<T> {
  Property(private value: T);
  get () { return this.value; }
  set(newValue: T) { this.value = newValue; }
}

const doc = {
  name: new Property("red"),
  age: new Property(2)
}
```

Maybe I have a syntax error because I'm writing it blindly but the idea should remain the same

**Comment by chrismichaelps** [comment]
@slavik57 

I was trying to do it differently, but it shows me the following error.


```typescript
type PC = Proxied<Cat>;

const doc: PC = null;
doc.name.set("red");
console.log(doc.name.get());
```

**error**
```shell
src/typetify.ts:30:7 - error TS2322: Type 'null' is not assignable to type 'Proxied<Cat>'.
30 const doc: PC = null;
```

**Comment by slavik57** [comment]
That is probably because Proxied is not a nullable object.
You can solve it either in some configuration of TypeScript compiler in the tsconfig file or by declaring the type like so:
```
type PC = Proxied<Cat> | null;
```
Not sure whether it should be `|` or `||`
But even if it will compile you'll have an error here because `doc` will be `null` so when you will do `doc.name` you will get an error.

I think you understand it wrong. When you create a type like you do, it is equivalent to creating an interface not a class.
So you cannot do `new PC()` or `doc: PC` and expect a real object to be created.

**Comment by chrismichaelps** [comment]
@slavik57 ,

Very grateful for your help.
